"""add role to user

Revision ID: 57df00399fc7
Revises: 
Create Date: 2025-06-05 01:30:24.765625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57df00399fc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False, server_default='user'))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('role')

    op.create_table('criteria_value',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('alternative_id', sa.INTEGER(), nullable=False),
    sa.Column('criteria_id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['alternative_id'], ['alternative.id'], ),
    sa.ForeignKeyConstraint(['criteria_id'], ['criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
